// <auto-generated />
using System;
using GameTrackerWpfClientApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameTrackerWpfClientApp.Data.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    partial class ClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("GameTracker.Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ServerVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ServerVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.Lap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPitLap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LapNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LapTime")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sector1")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sector2")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sector3")
                        .HasColumnType("REAL");

                    b.Property<Guid>("StintId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StintId", "LapNumber");

                    b.ToTable("Laps");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.LapInputTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CompressedChannels")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("LapId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Preview")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("PreviewSampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleRateHz")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LapId")
                        .IsUnique();

                    b.ToTable("LapInputTelemetry");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CarExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndReason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.Stint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OutLap")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("StintNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Stints");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.SyncMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSyncedVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityName")
                        .IsUnique();

                    b.ToTable("SyncMetadata");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.TelemetryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CarExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LapNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LapTime")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UploadedAtUtc", "RecordedAtUtc");

                    b.ToTable("LocalTelemetry");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LayoutName")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LengthMetres")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ServerVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.Lap", b =>
                {
                    b.HasOne("GameTracker.Domain.Entities.Stint", "Stint")
                        .WithMany("Laps")
                        .HasForeignKey("StintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stint");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.LapInputTelemetry", b =>
                {
                    b.HasOne("GameTracker.Domain.Entities.Lap", "Lap")
                        .WithOne("InputTelemetry")
                        .HasForeignKey("GameTracker.Domain.Entities.LapInputTelemetry", "LapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lap");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.Stint", b =>
                {
                    b.HasOne("GameTracker.Domain.Entities.Session", "Session")
                        .WithMany("Stints")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.Lap", b =>
                {
                    b.Navigation("InputTelemetry");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.Session", b =>
                {
                    b.Navigation("Stints");
                });

            modelBuilder.Entity("GameTracker.Domain.Entities.Stint", b =>
                {
                    b.Navigation("Laps");
                });
#pragma warning restore 612, 618
        }
    }
}
